CasaRural/Models/Furniture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CasaRural.Models
{
    public class Furniture
    {
        public int ID { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The field {0} can't be longer than 100 characters")]
        public String Name { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime BuyDate { get; set; }
        public Double High { get; set; }
        public Double Weight { get; set; }
        public String Image { get; set; }
        public Boolean Available { get; set; }
        public Boolean Active { get; set; }


        //Relationship Furniture
        [InverseProperty("Furniture")]
        List<Inventory> ListInventory { get; set; }

    }
}

CasaRural/Controllers/FurnituresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CasaRural.Data;
using CasaRural.Models;
using CasaRural.Filter;



namespace CasaRural.Controllers
{
    [ServiceFilter(typeof(SessionFilter))]
    public class FurnituresController : Controller
    {
        private readonly casaruralContext _context;

        public FurnituresController(casaruralContext context)
        {
            _context = context;
        }

        // GET: Furnitures
        public async Task<IActionResult> Index(String busqueda)
        {
            var furniture = _context.Furniture.Where(f => f.Active == true);
            if (!String.IsNullOrEmpty(busqueda))
            {
                furniture = _context.Furniture.Where(f => f.Name.Contains(busqueda));
            }
            return View(await furniture.ToListAsync());
        }

        // GET: Furnitures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var furniture = await _context.Furniture
                .FirstOrDefaultAsync(m => m.ID == id);
            if (furniture == null)
            {
                return NotFound();
            }

            return View(furniture);
        }

        // GET: Furnitures/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Furnitures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,BuyDate,High,Weight,Image,Available,Active")] Furniture furniture)
        {
            if (ModelState.IsValid)
            {
                furniture.Active = true;
                furniture.Available = true;
                _context.Add(furniture);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(furniture);
        }

        // GET: Furnitures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var furniture = await _context.Furniture.FindAsync(id);
            if (furniture == null)
            {
                return NotFound();
            }
            return View(furniture);
        }

        // POST: Furnitures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,BuyDate,High,Weight,Image,Available,Active")] Furniture furniture)
        {
            if (id != furniture.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(furniture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FurnitureExists(furniture.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(furniture);
        }

        // GET: Furnitures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var furniture = await _context.Furniture
                .FirstOrDefaultAsync(m => m.ID == id);
            if (furniture == null)
            {
                return NotFound();
            }
            
            return View(furniture);
        }

        // POST: Furnitures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var furniture = await _context.Furniture.FindAsync(id);
            var furnitureInventory = _context.Inventory.Where(f => f.FurnitureID.Equals(id) && furniture.Available == false).FirstOrDefault();
            if (furnitureInventory != null)
            {
                TempData["ErrorMessage"] = "El mueble esta siendo usado y no puede eliminarse";
                return RedirectToAction(nameof(Delete));
            }
            _context.Furniture.Remove(furniture);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FurnitureExists(int id)
        {
            return _context.Furniture.Any(e => e.ID == id);
        }

        //Ver todo los registros existentes
        public async Task<IActionResult> VerTodoLosRegistros()
        {
            return View(await _context.Furniture.ToListAsync());
        }

            //Borrado lógico.
            public async Task<IActionResult> BorradoLogico(int? id)
        {

            var furniture = await _context.Furniture.FindAsync(id);

           
            
            var furnitureInventory = _context.Inventory.Where(f => f.FurnitureID.Equals(id) && furniture.Available == false).FirstOrDefault();
            if (furnitureInventory != null)
            {
                TempData["ErrorMessage"] = "El mueble esta siendo usado y no puede eliminarse";
                return RedirectToAction(nameof(Index));
            }
            furniture.Active = false;
            furniture.Available = false;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

      

    }
}

CasaRural/Views/Furnitures/Create.cshtml
@model CasaRural.Models.Furniture

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Furniture</h4>
<hr />
<div class="container position-absolute top-50 start-50 translate-middle align-middle">

    <form class="row justify-content-center g-3" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-6">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="BuyDate" class="control-label"></label>
            <input asp-for="BuyDate" class="form-control" />
            <span asp-validation-for="BuyDate" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="High" class="control-label"></label>
            <input asp-for="High" class="form-control" />
            <span asp-validation-for="High" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Weight" class="control-label"></label>
            <input asp-for="Weight" class="form-control" />
            <span asp-validation-for="Weight" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Image" class="control-label"></label>
            <input asp-for="Image" class="form-control" />
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <div class="col-12 d-grid gap-2">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
        <div>
            <a class="btn btn-success col-12 d-grid gap-2" asp-action="Index">Back to List</a>
        </div>
    </form>
    </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CasaRural/Views/Furnitures/Delete.cshtml
@model CasaRural.Models.Furniture

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Furniture</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BuyDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BuyDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.High)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.High)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Available)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Available)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
@if (TempData["ErrorMessage"] != null)
{
<p class="text-danger">@TempData["ErrorMessage"]</p>
}

CasaRural/Views/Furnitures/Details.cshtml
@model CasaRural.Models.Furniture

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Furniture</h4>
    <hr />
    <!--
       <dl class="row">
           <dt class = "col-sm-2">
               @Html.DisplayNameFor(model => model.Name)
           </dt>
           <dd class = "col-sm-10">
               @Html.DisplayFor(model => model.Name)
           </dd>
           <dt class = "col-sm-2">
               @Html.DisplayNameFor(model => model.BuyDate)
           </dt>
           <dd class = "col-sm-10">
               @Html.DisplayFor(model => model.BuyDate)
           </dd>
           <dt class = "col-sm-2">
               @Html.DisplayNameFor(model => model.High)
           </dt>
           <dd class = "col-sm-10">
               @Html.DisplayFor(model => model.High)
           </dd>
           <dt class = "col-sm-2">
               @Html.DisplayNameFor(model => model.Weight)
           </dt>
           <dd class = "col-sm-10">
               @Html.DisplayFor(model => model.Weight)
           </dd>
           <dt class = "col-sm-2">
               @Html.DisplayNameFor(model => model.Image)
           </dt>
           <dd class = "col-sm-10">
               @Html.DisplayFor(model => model.Image)
           </dd>
           <dt class = "col-sm-2">
               @Html.DisplayNameFor(model => model.Available)
           </dt>
           <dd class = "col-sm-10">
               @Html.DisplayFor(model => model.Available)
           </dd>
           <dt class = "col-sm-2">
               @Html.DisplayNameFor(model => model.Active)
           </dt>
           <dd class = "col-sm-10">
               @Html.DisplayFor(model => model.Active)
           </dd>
       </dl>
        -->
</div>

<div class="card" style="width: 18rem;  margin: auto auto">
    <img src=" @Html.DisplayFor(model => model.Image)" class="card-img-top img-fluid img-thumbnail w-50"  alt="...">
    <div class="card-body">
        <h5 class="card-title"> @Html.DisplayFor(model => model.Name)</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@Html.DisplayNameFor(model => model.BuyDate) : @Html.DisplayFor(model => model.BuyDate)</li>
    </ul>
    <div class="card-body">
        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
        <a class="btn btn-success" asp-action="Index">Back to List</a>
    </div>
</div>

CasaRural/Views/Furnitures/Edit.cshtml
@model CasaRural.Models.Furniture

@{
    ViewData["Title"] = "Edit";
}


<div class="container position-absolute top-50 start-50 translate-middle align-middle">
    
    <form class="row justify-content-center g-3" asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="col-6">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="BuyDate" class="control-label"></label>
            <input asp-for="BuyDate" class="form-control" />
            <span asp-validation-for="BuyDate" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="High" class="control-label"></label>
            <input asp-for="High" class="form-control" />
            <span asp-validation-for="High" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Weight" class="control-label"></label>
            <input asp-for="Weight" class="form-control" />
            <span asp-validation-for="Weight" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Image" class="control-label"></label>
            <input asp-for="Image" class="form-control" />
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="Available" /> @Html.DisplayNameFor(model => model.Available)
            </label>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
            </label>
        </div>
        <div class="col-12 d-grid gap-2">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>

        <div>
            <a class="btn btn-success col-12 d-grid gap-2" asp-action="Index">Back to List</a>
        </div>
    </form>
    </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CasaRural/Views/Furnitures/Index.cshtml
@model IEnumerable<CasaRural.Models.Furniture>
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Index";
}

<h1>Furnitures</h1>

<p>
    <a type="button" class="btn btn-primary" asp-action="Create">Create New</a>
</p>

<form asp-controller="Furnitures" asp-action="Index" method="get">

    <div class="input-group mb-3">
        <button class="btn btn-outline-secondary" type="submit" id="button-addon1">Filter</button>
        <input type="text" name="busqueda" class="form-control" placeholder="Filter by name" aria-describedby="button-addon1">
    </div>
    <a asp-page="/Index">Back to full List</a>
</form>

    <table class="table table-info table-striped border border-warning">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BuyDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.High)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Weight)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Available)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ValueFor(modelItem => item.BuyDate, "{0:dd/MM/yyyy}")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.High) cm
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Weight) cm
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Available)
                    </td>

                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-down" viewBox="0 0 16 16">
                                    <path d="M7.646.146a.5.5 0 0 1 .708 0L10.207 2H14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h3.793L7.646.146zM1 7v3h14V7H1zm14-1V4a1 1 0 0 0-1-1h-3.793a1 1 0 0 1-.707-.293L8 1.207l-1.5 1.5A1 1 0 0 1 5.793 3H2a1 1 0 0 0-1 1v2h14zm0 5H1v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2zM2 4.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                                </svg>
                            </button>
                            <ul class="dropdown-menu btn-success " aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.ID">Edit</a></li>
                                <li><a class="dropdown-item " asp-action="Details" asp-route-id="@item.ID">Details</a></li>
                                <li><a class="dropdown-item " asp-action="BorradoLogico" asp-route-id="@item.ID">Delete</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
   
    <a type="button" class="btn btn-dark" asp-action="VerTodoLosRegistros"> See all records</a> 
    @if (TempData["ErrorMessage"] != null)
    {
        <p class="text-danger">@TempData["ErrorMessage"]</p>
    }

CasaRural/Views/Furnitures/VerTodoLosRegistros.cshtml
@model IEnumerable<CasaRural.Models.Furniture>

@{
    ViewData["Title"] = "Index";
}

<h1>List all of furnitures</h1>

<p>
    <a type="button" class="btn btn-primary" asp-action="Create">Create New</a>
</p>

    <table class="table table-info table-striped border border-warning">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BuyDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.High)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Weight)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Available)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Active)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ValueFor(modelItem => item.BuyDate, "{0:dd/MM/yyyy}")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.High) cm
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Weight) cm
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Available)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Active)
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-down" viewBox="0 0 16 16">
                                    <path d="M7.646.146a.5.5 0 0 1 .708 0L10.207 2H14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h3.793L7.646.146zM1 7v3h14V7H1zm14-1V4a1 1 0 0 0-1-1h-3.793a1 1 0 0 1-.707-.293L8 1.207l-1.5 1.5A1 1 0 0 1 5.793 3H2a1 1 0 0 0-1 1v2h14zm0 5H1v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2zM2 4.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                                </svg>
                            </button>
                            <ul class="dropdown-menu btn-success " aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.ID">Edit</a></li>
                                <li><a class="dropdown-item " asp-action="Details" asp-route-id="@item.ID">Details</a></li>
                                <li><a class="dropdown-item " asp-action="Delete" asp-route-id="@item.ID">Delete</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
   
    @if (TempData["ErrorMessage"] != null)
    {
        <p class="text-danger">@TempData["ErrorMessage"]</p>
    }