CasaRural/Models/RoomCleaning.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CasaRural.Models
{
    public class RoomCleaning
    {
        public int ID { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime CleanDate { get; set; }
        [StringLength(50, ErrorMessage = "The field {0} can't be longer than 50 characters")]
        public String Observations { get; set; }
        public Boolean Clean { get; set; }

        public Boolean Active { get; set; }


        //Relationship Employed

        [Display(Name = "Employed")]
        public int EmployedID { get; set; }
        [ForeignKey("EmployedID")]
        public Employed Employed { get; set; }

        //Relationship Room

        [Display(Name = "Room")]
        public int RoomID { get; set; }
        [ForeignKey("RoomID")]
        public Room Room { get; set; }
    }
}

CasaRural/Controllers/RoomCleaningsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CasaRural.Data;
using CasaRural.Models;
using Microsoft.AspNetCore.Http;
using CasaRural.Filter;


namespace CasaRural.Controllers
{
    [ServiceFilter(typeof(SessionFilter))]
    public class RoomCleaningsController : Controller
    {
        private readonly casaruralContext _context;

        public RoomCleaningsController(casaruralContext context)
        {
            _context = context;
        }

        // GET: RoomCleanings
        public async Task<IActionResult> Index(String busqueda)
        {
            var casaruralContext = _context.RoomCleaning.Include(r => r.Employed).Include(r => r.Room).Where(rc => rc.Active == true).OrderBy(r => r.CleanDate);
            var jobPosition = _context.JobPosition.Where(j => j.Name.Equals("Limpiador")).FirstOrDefault();
            var employed = _context.Employed.Include(u => u.UserAccount).Where(u => u.JobPostionID.Equals(jobPosition.ID) && u.UserAccountID.ToString().Equals(HttpContext.Session.GetString("id"))).FirstOrDefault();
            if(employed != null)
            {
                casaruralContext = _context.RoomCleaning.Include(r => r.Employed).Include(r => r.Room).Where(f => f.EmployedID.Equals(employed.ID)).OrderBy(r => r.CleanDate);
            }
            
            if (busqueda != null)
            {

                casaruralContext = _context.RoomCleaning.Include(r => r.Employed).Include(r => r.Room).Where(f => f.CleanDate >= DateTime.Parse(busqueda) && f.Clean == true).OrderBy(r => r.CleanDate);
            }

           
           
            
            return View(await casaruralContext.ToListAsync());
        }

        // GET: RoomCleanings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomCleaning = await _context.RoomCleaning
                .Include(r => r.Employed)
                .Include(r => r.Room)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (roomCleaning == null)
            {
                return NotFound();
            }

            return View(roomCleaning);
        }

        // GET: RoomCleanings/Create
        public IActionResult Create()
        {
            ViewData["EmployedID"] = new SelectList(_context.Employed, "ID", "Name");
            ViewData["RoomID"] = new SelectList(_context.Room, "ID", "Name");
            return View();
        }

        // POST: RoomCleanings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CleanDate,Observations,Clean,EmployedID,RoomID,Active")] RoomCleaning roomCleaning)
        {
            if (ModelState.IsValid)
            {
                var employed = _context.Employed.Where(e => e.ID.Equals(roomCleaning.EmployedID)).FirstOrDefault();
                var jobPosition = _context.JobPosition.Where(j => j.ID.Equals(employed.JobPostionID)).FirstOrDefault();
                if (!jobPosition.Name.Equals("Limpiador"))
                {
                    TempData["ErrorMessage"] = "El empleado que intenta asignar no es un limpiador.";
                    return RedirectToAction(nameof(Create));
                }
                roomCleaning.Active = true;
                _context.Add(roomCleaning);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployedID"] = new SelectList(_context.Employed, "ID", "Name", roomCleaning.EmployedID);
            ViewData["RoomID"] = new SelectList(_context.Room, "ID", "Name", roomCleaning.RoomID);
            return View(roomCleaning);
        }

        // GET: RoomCleanings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomCleaning = await _context.RoomCleaning.FindAsync(id);
            if (roomCleaning == null)
            {
                return NotFound();
            }
            ViewData["EmployedID"] = new SelectList(_context.Employed, "ID", "Name", roomCleaning.EmployedID);
            ViewData["RoomID"] = new SelectList(_context.Room, "ID", "Name", roomCleaning.RoomID);
            return View(roomCleaning);
        }

        // POST: RoomCleanings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,CleanDate,Observations,Clean,EmployedID,RoomID,Active")] RoomCleaning roomCleaning)
        {
            if (id != roomCleaning.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(roomCleaning);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomCleaningExists(roomCleaning.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployedID"] = new SelectList(_context.Employed, "ID", "Name", roomCleaning.EmployedID);
            ViewData["RoomID"] = new SelectList(_context.Room, "ID", "Name", roomCleaning.RoomID);
            return View(roomCleaning);
        }

        // GET: RoomCleanings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomCleaning = await _context.RoomCleaning
                .Include(r => r.Employed)
                .Include(r => r.Room)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (roomCleaning == null)
            {
                return NotFound();
            }

            return View(roomCleaning);
        }

        // POST: RoomCleanings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var roomCleaning = await _context.RoomCleaning.FindAsync(id);
            _context.RoomCleaning.Remove(roomCleaning);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomCleaningExists(int id)
        {
            return _context.RoomCleaning.Any(e => e.ID == id);
        }

        //Ver todo los registros existentes
        public async Task<IActionResult> VerTodoLosRegistros()
        {
            var casaruralContext = _context.RoomCleaning.Include(r => r.Employed).Include(r => r.Room);
            return View(await casaruralContext.ToListAsync());
        }

        //Borrado lógico.
        public async Task<IActionResult> BorradoLogico(int? id)
        {

            var roomCleaning = await _context.RoomCleaning.FindAsync(id);

            roomCleaning.Active = false;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

CasaRural/Views/RoomCleanings/Create.cshtml
@model CasaRural.Models.RoomCleaning

@{
    ViewData["Title"] = "Create";
}


<div class="container position-absolute top-50 start-50 translate-middle align-middle">
    <form class="row justify-content-center g-3" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-6">
            <label asp-for="CleanDate" class="control-label"></label>
            <input asp-for="CleanDate" class="form-control" />
            <span asp-validation-for="CleanDate" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Observations" class="control-label"></label>
            <input asp-for="Observations" class="form-control" />
            <span asp-validation-for="Observations" class="text-danger"></span>
        </div>

        <div class="col-6">
            <label asp-for="EmployedID" class="control-label"></label>
            <select asp-for="EmployedID" class="form-control" asp-items="ViewBag.EmployedID"></select>
        </div>
        <div class="col-6">
            <label asp-for="RoomID" class="control-label"></label>
            <select asp-for="RoomID" class="form-control" asp-items="ViewBag.RoomID"></select>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="Clean" /> @Html.DisplayNameFor(model => model.Clean)
            </label>
        </div>
        <div class="col-12 d-grid gap-2">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
        <div>
            <a class="btn btn-success col-12 d-grid gap-2" asp-action="Index">Back to List</a>
        </div>
    </form>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
@if (TempData["ErrorMessage"] != null)
{
    <p class="text-danger">@TempData["ErrorMessage"]</p>
}

CasaRural/Views/RoomCleanings/Delete.cshtml
@model CasaRural.Models.RoomCleaning

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RoomCleaning</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CleanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CleanDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observations)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observations)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clean)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clean)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employed.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CasaRural/Views/RoomCleanings/Details.cshtml
@model CasaRural.Models.RoomCleaning

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>RoomCleaning</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CleanDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CleanDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observations)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observations)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clean)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clean)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Employed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Employed.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.Name)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a class="btn btn-success" asp-action="Index">Back to List</a>
</div>

CasaRural/Views/RoomCleanings/Edit.cshtml
@model CasaRural.Models.RoomCleaning

@{
    ViewData["Title"] = "Edit";
}


<div class="container position-absolute top-50 start-50 translate-middle align-middle">
    <form class="row justify-content-center g-3" asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="col-6">
            <label asp-for="CleanDate" class="control-label"></label>
            <input asp-for="CleanDate" class="form-control" />
            <span asp-validation-for="CleanDate" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Observations" class="control-label"></label>
            <input asp-for="Observations" class="form-control" />
            <span asp-validation-for="Observations" class="text-danger"></span>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="Clean" /> @Html.DisplayNameFor(model => model.Clean)
            </label>
        </div>
        <div class="col-6">
            <label asp-for="EmployedID" class="control-label"></label>
            <select asp-for="EmployedID" class="form-control" asp-items="ViewBag.EmployedID"></select>
            <span asp-validation-for="EmployedID" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="RoomID" class="control-label"></label>
            <select asp-for="RoomID" class="form-control" asp-items="ViewBag.RoomID"></select>
            <span asp-validation-for="RoomID" class="text-danger"></span>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
            </label>
        </div>
        <div class="col-12 d-grid gap-2">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>

        <div>
            <a class="btn btn-success col-12 d-grid gap-2" asp-action="Index">Back to List</a>
        </div>
    </form>
    </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CasaRural/Views/RoomCleanings/Index.cshtml
@model IEnumerable<CasaRural.Models.RoomCleaning>
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Index";
}

<h1>Room Cleanigs</h1>
@if (!@Context.Session.GetString("rol").Equals("Limpiador"))
{
    <p>
        <a type="button" class="btn btn-primary" asp-action="Create">Create New</a>
    </p>
}
<form asp-controller="RoomCleanings" asp-action="Index" method="get">

    <div class="input-group mb-3">
        <button class="btn btn-outline-secondary" type="submit">Filter</button>
        <input type="date" name="busqueda" class="form-control" placeholder="Filter by clean date">
    </div>
    <a asp-page="/Index">Back to full List</a>
</form>
    <table class="table table-info table-striped border border-warning">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CleanDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Observations)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Clean)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Employed)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Room)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ValueFor(modelItem => item.CleanDate, "{0:dd/MM/yyyy}")
                        <!-- @Html.DisplayFor(modelItem => item.CleanDate) -->
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Observations)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Clean)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Employed.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Room.Name)
                    </td>

                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-down" viewBox="0 0 16 16">
                                    <path d="M7.646.146a.5.5 0 0 1 .708 0L10.207 2H14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h3.793L7.646.146zM1 7v3h14V7H1zm14-1V4a1 1 0 0 0-1-1h-3.793a1 1 0 0 1-.707-.293L8 1.207l-1.5 1.5A1 1 0 0 1 5.793 3H2a1 1 0 0 0-1 1v2h14zm0 5H1v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2zM2 4.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                                </svg>
                            </button>
                            <ul class="dropdown-menu btn-success " aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.ID">Edit</a></li>
                                @if (!@Context.Session.GetString("rol").Equals("Limpiador"))
                                {
                                    <span>
                                    <li> <a type="button" class="dropdown-item" asp-action="Details" asp-route-id="@item.ID">Details</a></li>
                                    <li> <a type="button" class="dropdown-item" asp-action="BorradoLogico" asp-route-id="@item.ID">Delete</a></li>
                                    </span>
                                }
                            </ul>
                        </div>

                    </td>

                </tr>
            }
        </tbody>
    </table>
    @if (@Context.Session.GetString("rol").Equals("Admin"))
    {
        <a type="button" class="btn btn-dark" asp-action="VerTodoLosRegistros"> See all records</a>
    }

CasaRural/Views/RoomCleanings/VerTodoLosRegistros.cshtml
@model IEnumerable<CasaRural.Models.RoomCleaning>

@{
    ViewData["Title"] = "Index";
}

<h1>List all of room cleanings</h1>

<p>
    <a type="button" class="btn btn-primary" asp-action="Create">Create New</a>
</p>
    <table class="table table-info table-striped border border-warning">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CleanDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Observations)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Clean)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Employed)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Room)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ValueFor(modelItem => item.CleanDate, "{0:dd/MM/yyyy}")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Observations)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Clean)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Employed.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Room.Name)
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-down" viewBox="0 0 16 16">
                                    <path d="M7.646.146a.5.5 0 0 1 .708 0L10.207 2H14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h3.793L7.646.146zM1 7v3h14V7H1zm14-1V4a1 1 0 0 0-1-1h-3.793a1 1 0 0 1-.707-.293L8 1.207l-1.5 1.5A1 1 0 0 1 5.793 3H2a1 1 0 0 0-1 1v2h14zm0 5H1v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2zM2 4.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                                </svg>
                            </button>
                            <ul class="dropdown-menu btn-success " aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.ID">Edit</a></li>
                                <li><a class="dropdown-item " asp-action="Details" asp-route-id="@item.ID">Details</a></li>
                                <li><a class="dropdown-item " asp-action="Delete" asp-route-id="@item.ID">Delete</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
   