CasaRural/Models/JobPosition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CasaRural.Models
{
    public class JobPosition
    {
        public int ID { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The field {0} can't be longer than 100 characters")]
        public String Name { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The field {0} can't be longer than 100 characters")]
        public String Description { get; set; }

        public Boolean Active { get; set; }


        //Relationship Employed

        [InverseProperty("JobPosition")]
        public List<Employed> ListEmployed { get; set; }
    }
}

CasaRural/Controllers/JobPositionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CasaRural.Data;
using CasaRural.Models;
using CasaRural.Filter;

namespace CasaRural.Controllers
{
    [ServiceFilter(typeof(SessionFilter))]
    public class JobPositionsController : Controller
    {
        private readonly casaruralContext _context;

        public JobPositionsController(casaruralContext context)
        {
            _context = context;
        }

        // GET: JobPositions
        public async Task<IActionResult> Index(String busqueda)
        {
            var jobPosition = _context.JobPosition.Where(j => j.Active == true);
            if (!String.IsNullOrEmpty(busqueda))
            {
                jobPosition = _context.JobPosition.Where(f => f.Name.Contains(busqueda));
            }
            return View(await jobPosition.ToListAsync());
        }

        // GET: JobPositions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobPosition = await _context.JobPosition
                .FirstOrDefaultAsync(m => m.ID == id);
            if (jobPosition == null)
            {
                return NotFound();
            }

            return View(jobPosition);
        }

        // GET: JobPositions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: JobPositions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Description,Active")] JobPosition jobPosition)
        {
            if (ModelState.IsValid)
            {
                jobPosition.Active = true;
                _context.Add(jobPosition);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jobPosition);
        }

        // GET: JobPositions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobPosition = await _context.JobPosition.FindAsync(id);
            if (jobPosition == null)
            {
                return NotFound();
            }
            return View(jobPosition);
        }

        // POST: JobPositions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Description,Active")] JobPosition jobPosition)
        {
            if (id != jobPosition.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jobPosition);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobPositionExists(jobPosition.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jobPosition);
        }

        // GET: JobPositions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobPosition = await _context.JobPosition
                .FirstOrDefaultAsync(m => m.ID == id);
            if (jobPosition == null)
            {
                return NotFound();
            }

            return View(jobPosition);
        }

        // POST: JobPositions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jobPosition = await _context.JobPosition.FindAsync(id);
            _context.JobPosition.Remove(jobPosition);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobPositionExists(int id)
        {
            return _context.JobPosition.Any(e => e.ID == id);
        }

        //Ver todo los registros existentes
        public async Task<IActionResult> VerTodoLosRegistros()
        {
            return View(await _context.JobPosition.ToListAsync());
        }

        //Borrado lógico.
        public async Task<IActionResult> BorradoLogico(int? id)
        {

            var jobPosition = await _context.JobPosition.FindAsync(id);

            jobPosition.Active = false;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

CasaRural/Views/JobPositions/Create.cshtml
@model CasaRural.Models.JobPosition

@{
    ViewData["Title"] = "Create";
}

<div class="container position-absolute top-50 start-50 translate-middle align-middle">
    <form class="row justify-content-center g-3" asp-action="Create">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-6">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Description" class="control-label"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="col-12 d-grid gap-2">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>

        <div>
            <a class="btn btn-success col-12 d-grid gap-2" asp-action="Index">Back to List</a>
        </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CasaRural/Views/JobPositions/Delete.cshtml
@model CasaRural.Models.JobPosition

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JobPosition</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CasaRural/Views/JobPositions/Details.cshtml
@model CasaRural.Models.JobPosition

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>JobPosition</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a class="btn btn-success" asp-action="Index">Back to List</a>
</div>

CasaRural/Views/JobPositions/Edit.cshtml
@model CasaRural.Models.JobPosition

@{
    ViewData["Title"] = "Edit";
}


<div class="container position-absolute top-50 start-50 translate-middle align-middle">
    <form  class="row justify-content-center g-3" asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="col-6">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Description" class="control-label"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
            </label>
        </div>
        <div class="col-12 d-grid gap-2">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>

        <div>
            <a class="btn btn-success col-12 d-grid gap-2" asp-action="Index">Back to List</a>
        </div>
    </form>
    </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CasaRural/Views/JobPositions/Index.cshtml
@model IEnumerable<CasaRural.Models.JobPosition>
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Index";
}

<h1>Job Positions</h1>

<p>
    <a type="button" class="btn btn-primary" asp-action="Create">Create New</a>
</p>
<form asp-controller="JobPositions" asp-action="Index" method="get">

    <div class="input-group mb-3">
        <button class="btn btn-outline-secondary" type="submit" id="button-addon1">Filter</button>
        <input type="text" name="busqueda" class="form-control" placeholder="Filter by name" aria-describedby="button-addon1">
    </div>
    <a asp-page="/Index">Back to full List</a>
</form>
    <table class="table table-info table-striped border border-warning">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-down" viewBox="0 0 16 16">
                                    <path d="M7.646.146a.5.5 0 0 1 .708 0L10.207 2H14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h3.793L7.646.146zM1 7v3h14V7H1zm14-1V4a1 1 0 0 0-1-1h-3.793a1 1 0 0 1-.707-.293L8 1.207l-1.5 1.5A1 1 0 0 1 5.793 3H2a1 1 0 0 0-1 1v2h14zm0 5H1v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2zM2 4.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                                </svg>
                            </button>
                            <ul class="dropdown-menu btn-success " aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.ID">Edit</a></li>
                                <li><a class="dropdown-item " asp-action="Details" asp-route-id="@item.ID">Details</a></li>
                                <li><a class="dropdown-item " asp-action="BorradoLogico" asp-route-id="@item.ID">Delete</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @if (@Context.Session.GetString("rol").Equals("Admin"))
    {
        <a type="button" class="btn btn-dark" asp-action="VerTodoLosRegistros"> See all records</a>
    }

CasaRural/Views/JobPositions/VerTodoLosRegistros.cshtml
@model IEnumerable<CasaRural.Models.JobPosition>

@{
    ViewData["Title"] = "Index";
}

<h1>List all of job positions</h1>

<p>
    <a type="button" class="btn btn-primary" asp-action="Create">Create New</a>
</p>
    <table class="table table-info table-striped border border-warning">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-down" viewBox="0 0 16 16">
                                    <path d="M7.646.146a.5.5 0 0 1 .708 0L10.207 2H14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h3.793L7.646.146zM1 7v3h14V7H1zm14-1V4a1 1 0 0 0-1-1h-3.793a1 1 0 0 1-.707-.293L8 1.207l-1.5 1.5A1 1 0 0 1 5.793 3H2a1 1 0 0 0-1 1v2h14zm0 5H1v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2zM2 4.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                                </svg>
                            </button>
                            <ul class="dropdown-menu btn-success " aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.ID">Edit</a></li>
                                <li><a class="dropdown-item " asp-action="Details" asp-route-id="@item.ID">Details</a></li>
                                <li><a class="dropdown-item " asp-action="Delete" asp-route-id="@item.ID">Delete</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>