CasaRural/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CasaRural.Models
{
    public class Room
    {
        public int ID { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "The field {0} can't be longer than 50 characters")]
        public String Name { get; set; }
        public int NumberRoom { get; set; }
        public String Image { get; set; }

        public Boolean Active { get; set; }

        //Relationship Booking

        [InverseProperty("Room")]
        public List<Booking> ListBooking { get; set; }

        //Relationship RoomCleaning
        [InverseProperty("Room")]
        public List<RoomCleaning> ListRoomCleaning { get; set; }

        //Relationship TypeRoom

        [Display(Name = "TypeRoom")]
        public int TypeRoomID { get; set; }
        [ForeignKey("TypeRoomID")]
        public TypeRoom TypeRoom { get; set; }

        //Relationship InventoryHasRoom

        [InverseProperty("Room")]

        List<Inventory> ListInventory { get; set; }

       
    }
}

CasaRural/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CasaRural.Data;
using CasaRural.Models;
using CasaRural.Filter;

namespace CasaRural.Controllers
{
    [ServiceFilter(typeof(SessionFilter))]
    public class RoomsController : Controller
    {
        private readonly casaruralContext _context;

        public RoomsController(casaruralContext context)
        {
            _context = context;
        }

        // GET: Rooms
        public async Task<IActionResult> Index(String busquedaInicial, String busquedaFinal)
        {
            
            var casaruralContext = _context.Room.Include(r => r.TypeRoom).Where(r => r.Active == true);
            try
            {
                this.PlaningOcupacion(busquedaInicial, busquedaFinal);
            }
            catch(FormatException e)
            {
                TempData["ErrorMessage"] = "El formato de fecha no es correcto.";
                return RedirectToAction(nameof(Index));
            }
            return View(await casaruralContext.ToListAsync());
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .Include(r => r.TypeRoom)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            ViewData["TypeRoomID"] = new SelectList(_context.TypeRoom, "ID", "Description");
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,NumberRoom,Image,TypeRoomID,Active")] Room room)
        {
            if (ModelState.IsValid)
            {
                room.Active = true;
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TypeRoomID"] = new SelectList(_context.TypeRoom, "ID", "Description", room.TypeRoomID);
            return View(room);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["TypeRoomID"] = new SelectList(_context.TypeRoom, "ID", "Description", room.TypeRoomID);
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,NumberRoom,Image,TypeRoomID,Active")] Room room)
        {
            if (id != room.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TypeRoomID"] = new SelectList(_context.TypeRoom, "ID", "Description", room.TypeRoomID);
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .Include(r => r.TypeRoom)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Room.FindAsync(id);
            _context.Room.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Room.Any(e => e.ID == id);
        }

        //Ver todo los registros existentes
        public async Task<IActionResult> VerTodoLosRegistros()
        {
            var casaruralContext = _context.Room.Include(r => r.TypeRoom);
            return View(await casaruralContext.ToListAsync());
        }

        //Borrado lógico.
        public async Task<IActionResult> BorradoLogico(int? id)
        {

            var room = await _context.Room.FindAsync(id);

            room.Active = false;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> PlaningOcupacion(String busquedaInicial, String busquedaFinal)
        {
            var rooms = new List<Room>();
            
           
            if (busquedaInicial != null && busquedaFinal != null)
            {
                var booking = _context.Booking.Include(b => b.Customer).Include(b => b.Diet).Include(b => b.Room).Where(b => b.BookingStartDate >= DateTime.Parse(busquedaInicial) && b.BookingEndDate <= DateTime.Parse(busquedaFinal)).ToList();
                foreach (Booking book in booking)
                {
                    rooms = _context.Room.Include(r => r.TypeRoom).Where(r => r.ID.Equals(book.RoomID)).ToList();
                  
                }
                ViewBag.booking = booking;

            }
            ViewData["BusquedaInicial"] = busquedaInicial;
            ViewData["BusquedaFinal"] = busquedaFinal;
            
           

            return View(rooms);
        }
    }
}

CasaRural/Views/Rooms/Create.cshtml
@model CasaRural.Models.Room

@{
    ViewData["Title"] = "Create";
}


<div class="container position-absolute top-50 start-50 translate-middle align-middle">
    <form class="row justify-content-center g-3" asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-6">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="NumberRoom" class="control-label"></label>
            <input asp-for="NumberRoom" class="form-control" />
            <span asp-validation-for="NumberRoom" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Image" class="control-label"></label>
            <input asp-for="Image" class="form-control" />
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="TypeRoomID" class="control-label"></label>
            <select asp-for="TypeRoomID" class="form-control" asp-items="ViewBag.TypeRoomID"></select>
        </div>
        <div class="col-12 d-grid gap-2">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
        <div>
            <a class="btn btn-success col-12 d-grid gap-2" asp-action="Index">Back to List</a>
        </div>
    </form>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CasaRural/Views/Rooms/Delete.cshtml
@model CasaRural.Models.Room

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberRoom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberRoom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeRoom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeRoom.Description)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CasaRural/Views/Rooms/Details.cshtml
@model CasaRural.Models.Room

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Room</h4>
    <!--
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberRoom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberRoom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeRoom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeRoom.Description)
        </dd>
    </dl>
        -->

    <div class="card" style="width: 18rem; margin: auto auto">
        <img src=" @Html.DisplayFor(model => model.Image)" class="card-img-top  img-fluid img-thumbnail w-50" alt="...">
        <div class="card-body">
            <h5 class="card-title"> @Html.DisplayFor(model => model.Name)</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Número de Habitación: @Html.DisplayFor(model => model.NumberRoom)</li>
        </ul>
        <div class="card-body">
            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
            <a class="btn btn-success" asp-action="Index">Back to List</a>
        </div>
    </div>

CasaRural/Views/Rooms/Edit.cshtml
@model CasaRural.Models.Room

@{
    ViewData["Title"] = "Edit";
}


<div class="container position-absolute top-50 start-50 translate-middle align-middle">
    <form class="row justify-content-center g-3" asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="col-6">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="NumberRoom" class="control-label"></label>
            <input asp-for="NumberRoom" class="form-control" />
            <span asp-validation-for="NumberRoom" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Image" class="control-label"></label>
            <input asp-for="Image" class="form-control" />
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="TypeRoomID" class="control-label"></label>
            <select asp-for="TypeRoomID" class="form-control" asp-items="ViewBag.TypeRoomID"></select>
            <span asp-validation-for="TypeRoomID" class="text-danger"></span>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
            </label>
        </div>
        <div class="col-12 d-grid gap-2">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>

        <div>
            <a class="btn btn-success col-12 d-grid gap-2" asp-action="Index">Back to List</a>
        </div>
    </form>
    </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CasaRural/Views/Rooms/Index.cshtml
@model IEnumerable<CasaRural.Models.Room>
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Index";
}

<h1>Rooms</h1>
@if (!@Context.Session.GetString("rol").Equals("Jefe de Mantenimiento"))
{
    <p>
        <a type="button" class="btn btn-primary" asp-action="Create">Create New</a>
    </p>
}
    @if (!@Context.Session.GetString("rol").Equals("Jefe de Mantenimiento"))
    {
        <form asp-controller="Rooms" asp-action="PlaningOcupacion" method="get">
            <div class="input-group">
                <button class="btn btn-outline-secondary" type="submit">Filter between date</button>
                <input type="date" name="busquedaInicial" placeholder="Filter first date" aria-label="Busqueda Inicial" class="form-control">
                <input type="date" name="busquedaFinal" placeholder="Filter second date" aria-label="Busqueda Final" class="form-control">
            </div>
        </form>
    }
    <br />
        <table class="table table-info table-striped border border-warning">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NumberRoom)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.TypeRoom)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumberRoom)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.TypeRoom.Name)
                        </td>
                        <td>
                            <div class="btn-group">
                                <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-down" viewBox="0 0 16 16">
                                        <path d="M7.646.146a.5.5 0 0 1 .708 0L10.207 2H14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h3.793L7.646.146zM1 7v3h14V7H1zm14-1V4a1 1 0 0 0-1-1h-3.793a1 1 0 0 1-.707-.293L8 1.207l-1.5 1.5A1 1 0 0 1 5.793 3H2a1 1 0 0 0-1 1v2h14zm0 5H1v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2zM2 4.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                                    </svg>
                                </button>
                                <ul class="dropdown-menu btn-success " aria-labelledby="dropdownMenuButton1">
                                    @if (!@Context.Session.GetString("rol").Equals("Jefe de Mantenimiento"))
                                    {
                                        <li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.ID">Edit</a></li>
                                    }
                                    <li><a class="dropdown-item " asp-action="Details" asp-route-id="@item.ID">Details</a></li>
                                    <li><a class="dropdown-item " asp-action="BorradoLogico" asp-route-id="@item.ID">Delete</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @if (@Context.Session.GetString("rol").Equals("Admin"))
        {
            <a type="button" class="btn btn-dark" asp-action="VerTodoLosRegistros"> See all records</a>
        }
        @if (TempData["ErrorMessage"] != null)
        {
            <p class="text-danger">@TempData["ErrorMessage"]</p>
        }

CasaRural/Views/Rooms/PlaningOcupacion.cshtml
@model IEnumerable<CasaRural.Models.Room>
@using Microsoft.AspNetCore.Http;



<h1>Planing de ocupación</h1>

<table class="table table-info table-striped border border-warning">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberRoom)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.TypeRoom)
            </th>
            <th>
               Start Date:
            </th>
            <th>
                End Date:
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberRoom)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TypeRoom.Name)
            </td>
            @if (ViewBag.booking != null)
            {
                <td>
                    @foreach (Booking o in ViewBag.booking)
                    {
                        @o.BookingStartDate.ToString("dd/MM/yyyy") <br />
                    }
                </td>
            <td>
                @foreach (Booking o in ViewBag.booking)
                {
                    @o.BookingEndDate.ToString("dd/MM/yyyy") <br />
                }
            </td>
            }
        </tr>
        }
    </tbody>
</table>
<div>
    <a class="btn btn-success" asp-action="Index">Back to List</a>
</div>

CasaRural/Views/Rooms/VerTodoLosRegistros.cshtml
@model IEnumerable<CasaRural.Models.Room>

@{
    ViewData["Title"] = "Index";
}

<h1>List all of rooms</h1>

<p>
    <a type="button" class="btn btn-primary" asp-action="Create">Create New</a>
</p>
    <table class="table table-info table-striped border border-warning">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumberRoom)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.TypeRoom)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberRoom)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.TypeRoom.Name)
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-menu-down" viewBox="0 0 16 16">
                                    <path d="M7.646.146a.5.5 0 0 1 .708 0L10.207 2H14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h3.793L7.646.146zM1 7v3h14V7H1zm14-1V4a1 1 0 0 0-1-1h-3.793a1 1 0 0 1-.707-.293L8 1.207l-1.5 1.5A1 1 0 0 1 5.793 3H2a1 1 0 0 0-1 1v2h14zm0 5H1v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2zM2 4.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
                                </svg>
                            </button>
                            <ul class="dropdown-menu btn-success " aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.ID">Edit</a></li>
                                <li><a class="dropdown-item " asp-action="Details" asp-route-id="@item.ID">Details</a></li>
                                <li><a class="dropdown-item " asp-action="Delete" asp-route-id="@item.ID">Delete</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>